name: pyteseo-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - ipykernel
  - matplotlib
  - geojson
  - pytest
  - flit
  - black
  - sphinx
  - myst-parser
  - myst-nb
  - furo
  - sphinx-autoapi
  - sphinx_rtd_theme
  